### ISSUE TITLE
[FEATURE]: Add advanced time handling

### ISSUE THREAD

**Issue by dmvict** [rumos-io/gears#142]
### Feature description

The x-modules occasionally utilize timestamps from the context and perform mathematical operations using them. To carry out these operations, we convert the timestamps to `chrono` types. However, this conversion process is fallible and it would be preferable to avoid it altogether. 

I believe it is possible to incorporate the necessary conversions and logic directly into the Tendermint Timestamp type, thereby eliminating the need for additional time-related processing within the modules.

**Comment by joneskm** [comment]
Done in https://github.com/rumos-io/gears/pull/215
